//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tour
    {
        public Tour()
        {
            this.Hotel = new HashSet<Hotel>();
            this.Type = new HashSet<Type>();
        }
    
        public int id { get; set; }
        public Nullable<int> TicketCount { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public byte[] ImagePreview { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<bool> IsActual { get; set; }
    
        public virtual ICollection<Hotel> Hotel { get; set; }
        public virtual ICollection<Type> Type { get; set; }
    }
}
